### ISSUE TITLE
LDP Station not Powerd

### ISSUE THREAD

**Issue by PhilSBG** [whisky-actual/JAS-39-C-by-Whisky-Acutal#7]
No matter what Litening/Datalink/Jammingpod, all three do not work on the LDP station.

**Comment by TheonlyEggroll** [comment]
Choose loadout in ME - make sure you have

LDR on both pylon 4 and pylon LDP

2

In cockpit-Rearm - Clear or rearm pylon 4

as you desire

3

Wait for rearm to complete

4

Eject cartridge, open canopy and request Update DTC from ground crew

5

Load cartridge and update SMS

6



Switch CLDP off and on

**Comment by PhilSBG** [comment]
Sorry, I tried several times and unfortunately it doesn't work and I don't have any other mods installed.

**Comment by whisky-actual** [comment]
I will be posting a video shortly about the process, hold on
